export const MATH_SUBJECT_GUIDE = [
  '**수학 과목 요약 가이드:**',
  '- 핵심 정의/공식/성질을 먼저 정리',
  '- 계산 과정은 한두 단계로 요약하고, 실수할 수 있는 포인트(부호/분모/괄호) 강조',
  '- 정리된 핵심 정리 개념을 바탕으로 도형, 그래프 와 함께 보며 이해할 수 있도록 설명과 일치하는 적절한 도형과, 그래프를 생성',
  '- 기하/도형이면 도형 성질과 보조선/각 관계 중심으로 정리',
  '- **핵심 정리 구성**: 수업에서 다룬 핵심 개념 3~5개를 중심으로 순서대로 정리',
  '- **가독성**: 한 문장은 30~40자 내외로 끊어 읽기 좋게 작성',
  '- **흐름 유지**: 수업에서 진행한 풀이/설명 흐름의 순서를 유지',
  '',
  '**도형/그래프 JSON 생성 가이드:**',
  '- 수업에서 다룬 도형이나 그래프가 있으면 반드시 해당 핵심 정리 내용에 맞는 예시 도형 또는 그래프를 JSON 형태로 포함',
  '- 도형: type, vertices(좌표 배열), labels(꼭짓점 라벨), description',
  '- 그래프: type, points(좌표 배열), function(함수식), description',
  '- 좌표는 상대 좌표로 표현 (예: [[0, 0], [100, 0], [50, 86.6]])',
  '- function은 정확한 수식으로 (파싱 가능하게)',
  '- shapes는 배열로 여러 도형 조합 가능',
  '- annotations로 치수, 각도, 레이블 추가',
  '',
  '**그래표 도형 json 형식 예시**(매우 중요 - 시각 자료 중심)',
  '- **중요: geometricShapes는 문제를 만드는 것이 아니라, 핵심 정리 설명을 보조하는 시각 자료입니다**',
  '- 그래프 json 예시 (시각 자료): {"type": "graph", "function": "y = -x² + 4x + 5", "xRange": [-1, 6], "yRange": [0, 12], "xLabel": "시간(초)", "yLabel": "높이(m)", "specialPoints": [{"x": 2, "y": 9, "label": "최고점", "color": "red"}], "gridLines": true, "showVertex": true}',
  '- 도형 json 예시 (시각 자료): {"type": "geometry", "shapes": [{"type": "line", "points": [[50, 250], [50, 130]], "stroke": "#1e293b", "strokeWidth": 4, "label": "건물"}, ...], "annotations": [{"type": "text", "position": [30, 190], "text": "12m", "fontSize": 16, "color": "#1e293b"}, {"type": "arc", "center": [50, 130], "radius": 30, "startAngle": 0, "endAngle": 30, "label": "30°"}, ...]}',
  '- **참고: question, choices, answer는 선택사항입니다. 수업에서 실제 문제를 풀었다면 포함할 수 있지만, 핵심 정리 설명을 보조하는 시각 자료가 우선입니다**'
].join('\n');
